name: Build & Push Images (main)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_number }}

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        include:
          - name: product-service
            context: example-1/backend/product_Service
          - name: frontend
            context: example-1/frontend

    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        uses: azure/cli@v2
        with:
          inlineScript: az acr login --name ${{ vars.ACR_NAME }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ vars.ACR_LOGIN_SERVER }}/${{ matrix.name }}:${{ env.IMAGE_TAG }}
