name: Build & Push Images (main)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_number }}

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        include:
          - name: product-service
            context: example-1/backend/product_Service
          - name: frontend
            context: example-1/frontend

    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Use docker/login-action to authenticate to ACR (works perfectly for build-push-action)
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_LOGIN_SERVER }}
          username: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ vars.ACR_LOGIN_SERVER }}/${{ matrix.name }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
