name: PR CI (basic)

on:
  pull_request:
    branches:
      - dev
      - main

concurrency:
  group: pr-ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # keep the CI minimal—it's only here to satisfy the required status check
      - name: Sanity check
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "PR #${{ github.event.pull_request.number }} OK"
