name: PR CI (basic)

on:
  pull_request:
    branches: [dev, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-ci:
    uses: ./.github/workflows/reusable-ci.yml
